# Generated by Django 5.2 on 2025-05-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='equipment_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
