# Generated by Django 5.2 on 2025-05-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_device_equipment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned_nurses',
            field=models.ManyToManyField(blank=True, related_name='devices', to='main_app.nurse'),
        ),
    ]
