# Generated by Django 5.2 on 2025-05-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_device_assigned_nurses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartrequest',
            name='part_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
