# Generated by Django 5.2 on 2025-05-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_sparepartrequest_part_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='technical_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
